/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeoshimemoria;

import java.awt.Color;
import oshi.SimpleSystemInfo;

/**
 *
 * @author ILEVINO
 */
public class MonitoramentoLocal extends javax.swing.JFrame {

    
       private boolean enableDebugUpdateLabels = true;
    private int indexOfCurrentDisk;
    private int indexOfCurrentNetworkInterface;
    private int maxProcesses = 10;
    
    
    
       
    public void atualizacaoVariaveis() {
        new Thread() {
            @Override
            public void run() {
                while (true) {

                    //memoria
                    porcentoMemoria1.setText(SimpleSystemInfo.getMemoryUsedPercentageAsString() + "%");
                    usoMemoria.setText(SimpleSystemInfo.getMemoryUsedAsString());
                    totalMemoria.setText(SimpleSystemInfo.getMemoryCapacityAsString());
                    
                    
                    //CPU
                    
                    porcentoCPU.setText(SimpleSystemInfo.getCpuUsedPercentageAsDouble()+ "%");
                    usoCPU.setText(SimpleSystemInfo.getCpuCurrentFrequencyAsString());
                 
                    //Disco
                    
                    porcentoDISCO.setText(SimpleSystemInfo.getDisksUsedPercentageAsString()[0] + "%");
                    usoDISCO.setText(SimpleSystemInfo.getDisksUsedAsString()[0]);//pegando o primeiro disco do PC
                    totalDISCO.setText(SimpleSystemInfo.getDisksCapacityAsString()[0]);

                    
                    //processos
                  
                    tempName = tempPid = tempCpuPercent = tempRam = tempRamPercent = "";
                    for (String[] process : SimpleSystemInfo.getProcessesAsStringTable()) {
                        tempName += (process[0].length() > 13 ? process[0].substring(0, 13) : process[0]) + "\n";
                        tempPid += process[1] + "\n";
                        tempCpuPercent += process[2] + "\n";
                        tempRam += process[3] + "\n";
                        tempRamPercent += process[4] + "\n";
                    }                    
                    labelProcessName.setText(tempName.substring(0, tempName.length() - 1));
                    labelProcessPid.setText(tempPid.substring(0, tempPid.length() - 1));
                    labelProcessCpuPercent.setText(tempCpuPercent.substring(0, tempCpuPercent.length() - 1));
                    labelProcessRam.setText(tempRam.substring(0, tempRam.length() - 1));
                    labelProcessRamPercent.setText(tempRamPercent.substring(0, tempRamPercent.length() - 1));

                    //não mexer
                    try {
                        Thread.sleep(80);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();//thread
    }//attualizaçao 

    /**
     * Creates new form SwingMemoria
     */
    public MonitoramentoLocal() {
        initComponents();
        atualizacaoVariaveis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MemoriaLabel = new javax.swing.JLabel();
        barraMemoria = new javax.swing.JLabel();
        usoMemoria = new javax.swing.JLabel();
        totalMemoria = new javax.swing.JLabel();
        usoLabel1 = new javax.swing.JLabel();
        porcentoMemoria1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CPULabel = new javax.swing.JLabel();
        porcentoCPU = new javax.swing.JLabel();
        usoLabel = new javax.swing.JLabel();
        usoCPU = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        porcentoDISCO = new javax.swing.JLabel();
        usoLabel2 = new javax.swing.JLabel();
        usoDISCO = new javax.swing.JLabel();
        DISCOLabel = new javax.swing.JLabel();
        barraDISCO = new javax.swing.JLabel();
        totalDISCO = new javax.swing.JLabel();
        panelProcess = new javax.swing.JPanel();
        imageProcess = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem3 = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem5 = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem6 = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem7 = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem8 = new javax.swing.JLabel();
        labelProcessSimboloPorcentagem9 = new javax.swing.JLabel();
        labelProcessName = new javax.swing.JTextArea();
        labelProcessPid = new javax.swing.JTextArea();
        labelProcessCpuPercent = new javax.swing.JTextArea();
        labelProcessRam = new javax.swing.JTextArea();
        labelProcessRamPercent = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MONITORAMENTO LOCAL");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeoshimemoria/LogoHawkEyee.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        MemoriaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeoshimemoria/imagens/memoria.png"))); // NOI18N

        barraMemoria.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        barraMemoria.setForeground(new java.awt.Color(58, 65, 84));
        barraMemoria.setText("/");

        usoMemoria.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        usoMemoria.setText("06,70 GiB");

        totalMemoria.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        totalMemoria.setText("16,00 GiB");

        usoLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usoLabel1.setText("USO");

        porcentoMemoria1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        porcentoMemoria1.setText("36%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(MemoriaLabel)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(usoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(porcentoMemoria1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(usoLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalMemoria)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(porcentoMemoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MemoriaLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        CPULabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeoshimemoria/imagens/cpu-512.png"))); // NOI18N

        porcentoCPU.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        porcentoCPU.setText("30,0%");

        usoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usoLabel.setText("USO");

        usoCPU.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        usoCPU.setText("06,70 ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CPULabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(porcentoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usoLabel))
                    .addComponent(usoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CPULabel)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentoCPU))
                        .addGap(18, 18, 18)
                        .addComponent(usoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        porcentoDISCO.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        porcentoDISCO.setText("100,00%");

        usoLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usoLabel2.setText("USO");

        usoDISCO.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        usoDISCO.setText("06,70 ");

        DISCOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeoshimemoria/imagens/HD.png"))); // NOI18N

        barraDISCO.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        barraDISCO.setForeground(new java.awt.Color(58, 65, 84));
        barraDISCO.setText("/");

        totalDISCO.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        totalDISCO.setText("16,00 GiB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(DISCOLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(usoDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(porcentoDISCO)))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(usoLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalDISCO)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DISCOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porcentoDISCO)
                            .addComponent(usoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usoDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDISCO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelProcess.setBackground(new java.awt.Color(255, 255, 255));
        panelProcess.setForeground(new java.awt.Color(0, 0, 0));
        panelProcess.setPreferredSize(new java.awt.Dimension(356, 130));

        imageProcess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testeoshimemoria/imagens/processo-icon.png"))); // NOI18N

        labelProcessSimboloPorcentagem3.setBackground(new java.awt.Color(0, 0, 0));
        labelProcessSimboloPorcentagem3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelProcessSimboloPorcentagem3.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem3.setText("TOP PROCESSOS");

        labelProcessSimboloPorcentagem5.setBackground(new java.awt.Color(102, 102, 102));
        labelProcessSimboloPorcentagem5.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem5.setText("Nome");

        labelProcessSimboloPorcentagem6.setBackground(new java.awt.Color(102, 102, 102));
        labelProcessSimboloPorcentagem6.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem6.setText("PID");

        labelProcessSimboloPorcentagem7.setBackground(new java.awt.Color(102, 102, 102));
        labelProcessSimboloPorcentagem7.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem7.setText("%CPU");

        labelProcessSimboloPorcentagem8.setBackground(new java.awt.Color(102, 102, 102));
        labelProcessSimboloPorcentagem8.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem8.setText("RAM");

        labelProcessSimboloPorcentagem9.setBackground(new java.awt.Color(102, 102, 102));
        labelProcessSimboloPorcentagem9.setForeground(new java.awt.Color(107, 107, 107));
        labelProcessSimboloPorcentagem9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProcessSimboloPorcentagem9.setText("%RAM");

        labelProcessName.setEditable(false);
        labelProcessName.setColumns(15);
        labelProcessName.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelProcessName.setForeground(new java.awt.Color(187, 187, 186));
        labelProcessName.setRows(8);
        labelProcessName.setText("loading...");
        labelProcessName.setDisabledTextColor(new java.awt.Color(153, 153, 154));

        labelProcessPid.setEditable(false);
        labelProcessPid.setColumns(10);
        labelProcessPid.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelProcessPid.setForeground(new java.awt.Color(187, 187, 186));
        labelProcessPid.setRows(8);

        labelProcessCpuPercent.setEditable(false);
        labelProcessCpuPercent.setColumns(10);
        labelProcessCpuPercent.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelProcessCpuPercent.setForeground(new java.awt.Color(187, 187, 186));
        labelProcessCpuPercent.setRows(8);

        labelProcessRam.setEditable(false);
        labelProcessRam.setColumns(11);
        labelProcessRam.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelProcessRam.setForeground(new java.awt.Color(187, 187, 186));
        labelProcessRam.setRows(8);

        labelProcessRamPercent.setEditable(false);
        labelProcessRamPercent.setColumns(9);
        labelProcessRamPercent.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        labelProcessRamPercent.setForeground(new java.awt.Color(187, 187, 186));
        labelProcessRamPercent.setRows(8);

        javax.swing.GroupLayout panelProcessLayout = new javax.swing.GroupLayout(panelProcess);
        panelProcess.setLayout(panelProcessLayout);
        panelProcessLayout.setHorizontalGroup(
            panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(imageProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProcessLayout.createSequentialGroup()
                        .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelProcessSimboloPorcentagem5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(labelProcessName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProcessLayout.createSequentialGroup()
                                .addComponent(labelProcessSimboloPorcentagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelProcessSimboloPorcentagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelProcessSimboloPorcentagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelProcessSimboloPorcentagem9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addGroup(panelProcessLayout.createSequentialGroup()
                                .addComponent(labelProcessPid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelProcessCpuPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelProcessRam, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelProcessRamPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))))
                    .addComponent(labelProcessSimboloPorcentagem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelProcessLayout.setVerticalGroup(
            panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProcessLayout.createSequentialGroup()
                        .addComponent(labelProcessSimboloPorcentagem3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProcessSimboloPorcentagem5)
                            .addComponent(labelProcessSimboloPorcentagem6)
                            .addComponent(labelProcessSimboloPorcentagem7)
                            .addComponent(labelProcessSimboloPorcentagem8)
                            .addComponent(labelProcessSimboloPorcentagem9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(labelProcessName, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(labelProcessPid)
                            .addComponent(labelProcessCpuPercent)
                            .addComponent(labelProcessRam)
                            .addComponent(labelProcessRamPercent))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoramentoLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPULabel;
    private javax.swing.JLabel DISCOLabel;
    private javax.swing.JLabel MemoriaLabel;
    private javax.swing.JLabel barraDISCO;
    private javax.swing.JLabel barraMemoria;
    private javax.swing.JLabel imageProcess;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextArea labelProcessCpuPercent;
    private javax.swing.JTextArea labelProcessName;
    private javax.swing.JTextArea labelProcessPid;
    private javax.swing.JTextArea labelProcessRam;
    private javax.swing.JTextArea labelProcessRamPercent;
    private javax.swing.JLabel labelProcessSimboloPorcentagem3;
    private javax.swing.JLabel labelProcessSimboloPorcentagem5;
    private javax.swing.JLabel labelProcessSimboloPorcentagem6;
    private javax.swing.JLabel labelProcessSimboloPorcentagem7;
    private javax.swing.JLabel labelProcessSimboloPorcentagem8;
    private javax.swing.JLabel labelProcessSimboloPorcentagem9;
    private javax.swing.JPanel panelProcess;
    private javax.swing.JLabel porcentoCPU;
    private javax.swing.JLabel porcentoDISCO;
    private javax.swing.JLabel porcentoMemoria1;
    private javax.swing.JLabel totalDISCO;
    private javax.swing.JLabel totalMemoria;
    private javax.swing.JLabel usoCPU;
    private javax.swing.JLabel usoDISCO;
    private javax.swing.JLabel usoLabel;
    private javax.swing.JLabel usoLabel1;
    private javax.swing.JLabel usoLabel2;
    private javax.swing.JLabel usoMemoria;
    // End of variables declaration//GEN-END:variables
 private int countDebugUpdate = 0;
    private String temp;
    private String tempName;
    private String tempPid;
    private String tempCpuPercent;
    private String tempRam;
    private String tempRamPercent;
}
